vm_blog_homepage:
    path:  /
    defaults: { _controller: VMBlogBundle:Default:index }

vm_blog_image_list:
    path:  /image
    defaults: { _controller: VMBlogBundle:Image:listimage}

vm_blog_biographie:
    path:  /biographie
    defaults: { _controller: VMBlogBundle:Default:bio}
    
vm_blog_commentaire_list:
  path:  /commentaire/{page}
  defaults: { _controller: VMBlogBundle:Commentaire:listcommentaire, page:1 }
  
vm_blog_commentaire_ajout:
    path:  /commentaire_ajout/
    defaults: { _controller: VMBlogBundle:Commentaire:ajoutcommentaire }    
    
vm_blog_commentaire_edit:
    path:  /commentaire_edit/{id}
    defaults: { _controller: VMBlogBundle:Commentaire:editcommentaire}
    options:
       expose: true
       
vm_blog_commentaire_supprime:
    path:  /commentaire_supprime/{id}
    defaults: { _controller: VMBlogBundle:Commentaire:supprimecommentaire}
    options:
        expose: true    
        
vm_blog_commentaire_user:
     path:  /commentaire_profile/{id}
     defaults: { _controller: VMBlogBundle:Commentaire:profilecommentaire}
     options:
        expose: true    