parameters:
#    vm_blog.example.class: VM\BlogBundle\Example

services:
  # activation des filtres text de twig pour les chaines de caracteres.
  twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }
 