<?php

namespace VM\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
    /**
     * Get commentairesacceptes1
     * @return Commentaire
     */
    public function getCommentairesAcceptes()
    {
     $query_builder = $this->createQueryBuilder('c');
     $query_builder->leftJoin('c.livre', 'l')
             ->addSelect('l')->where( $query_builder->expr()->like('l.titre', '"le monstre du Médoc%"'));
     
     //$this->_em->createQueryBuilder()->select('c')->from($this->_entityName, 'c');
     //$query_builder->join('c.livre', 'l', 'ON', 'l.titre like "Le monstre du%"');
     $query_builder->where($query_builder->expr()->like('c.statut', "'modere%'"))->orderBy('c.date', 'DESC');
     return $query_builder->getQuery()->getResult();
     }   

     /**
     * Get commentairesacceptes2
     * @return Commentaire
     */
    public function getCommentairesAcceptes_pagine($page,$commentaires_per_page)
    {
        
     $query_builder = $this->createQueryBuilder('c');
     $query_builder->leftJoin('c.livre', 'l')
                   ->addSelect('l')->where( $query_builder->expr()->like('l.titre', '"le monstre du Médoc%"'))
                   ->where($query_builder->expr()->like('c.statut', "'modere%'"))->orderBy('c.date', 'DESC');
     
     $query_builder->setFirstResult(($page * $commentaires_per_page) - $commentaires_per_page)
                   ->setMaxResults($commentaires_per_page);
            
    
     return $query_builder->getQuery()->getResult();
     }  

}
