<?php

namespace VM\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
     /**
     * Get imagesacceptes
     * @return Image
     */
    public function getImagesAcceptes()
    {
    $query_builder = $this->createQueryBuilder('i');
    $query_builder->leftJoin('i.livre', 'l');
    $query_builder->addSelect('l');//->where($query_builder->expr()->like('l.titre', '"le monstre du Médoc%"'));
    $query_builder->where($query_builder->expr()->like('i.url', ':prefixe'))
            ->setParameter('prefixe', 'image%');
    return $query_builder->getQuery()->getResult();
    }
     
}
