# Routes pour le blog
vm_blog:
    resource: "@VMBlogBundle/Resources/config/routing.yml"
    prefix:   /
    
 # Routes pour le module utilisateur
vm_user:
    resource: "@VMUserBundle/Resources/config/routing.yml"
    prefix:   /
    
# Routes ajax 
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Routes pour le système d'authentification des utilisateurs
login:
  pattern: /login
  defaults: { _controller: VMUserBundle:Security:login }
  
login_check:
  pattern:   /login_check  

login_failure:
    pattern: /login_failure
    defaults: { _controller: VMUserBundle:Security:failure } 
#m_userblog_profile_show:
 # pattern: /profile
  #defaults: { _controller: VMUserBundle:Profile:showprofile }
  
logout:
  pattern:   /logout    

#fos_user_security:
 #   resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
#fos_user_profile:
 #   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  #  prefix: /profile
 
#fos_user_register:
 #   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  #  prefix: /register
 
#fos_user_resetting:
  #  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
 #   prefix: /resetting
 
#fos_user_change_password:
 #   resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile


admin:
   path:  /admin
   defaults: { _controller: VMBlogBundle:Default:admin }